SELECT u.INTCVEUSUARIO, u.VCHUSUARIO, u.CHRTIPOUSUARIO, j.INTCVEJUGADOR, j.VCHNOMBRE 
FROM usuario u LEFT OUTER JOIN jugador j 
ON u.INTCVEUSUARIO = j.INTCVEUSUARIO
WHERE u.INTCVEUSUARIO = @idUsuario AND u.VCHPASSWORD = 