SELECT CONCAT(u.INTCVEUSUARIO,'-', u.VCHUSUARIO) as nombreUsuario , CONCAT(j.INTCVEJUGADOR, '-', j.VCHNOMBRE) as nombreJugador, j.INTCVEJUGADOR, j.INTCVEUSUARIO, j.VCHNOMBRE, j.GENERO, j.GRADO, j.FECHANACIMIENTO, j.FECHAINSCRIPCION
FROM [jugador] as j
JOIN USUARIO as u
ON u.INTCVEUSUARIO = j.INTCVEUSUARIO
